### ISSUE TITLE
Content_log unter 3.5.15

### ISSUE THREAD

**Issue by Acta2000** [Sascha-Brandhoff/content_log#1]
Hallo und herzlichen Dank für die Erweiterung. 

Ich habe einige Tests gemacht und folgendes festgestellt:
1. Es sind nur .html5 Templates da. Ist im Seitenlayout jedoch xhtml als Quelle ausgewählt, dann erscheint eine entsprechende Fehlermeldung. Problem kann durch einfaches Umbenennen/ Duplizieren gelöst werden. 
2. Sind keine neuen Änderungen vorhanden, so wird ein Link auf die Startseite der Website gesetzt. Ganz ohne weitere Informationen. Es erscheint zudem ein "Warning"

Warning: Creating default object from empty value in system\modules\content_log\modules\ModuleContentLog.php on line 96

system\modules\content_log\modules\ModuleContentLog.php(96): __error(2, 'Creating defaul...', 'D:\xampp\htdocs...', 96, Array)
#1 system\modules\core\modules\Module.php(287): Contao\ModuleContentLog->compile()
#2 system\modules\content_log\modules\ModuleContentLog.php(30): Contao\Module->generate()
#3 system\modules\core\library\Contao\Controller.php(321): Contao\ModuleContentLog->generate()
#4 system\modules\core\pages\PageRegular.php(133): Contao\Controller::getFrontendModule(Object(Contao\ModuleModel), 'left')
#5 system\modules\core\controllers\FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#6 index.php(20): Contao\FrontendIndex->run()
#7 {main}

Verwenden tue ich die Version aus der Erweiterungsverwaltung

**Comment by Sascha-Brandhoff** [comment]
Hallo @Acta2000 ich werd mich drum kümmern das ganze zu fixen.
